# Generated by Django 6.0 on 2026-03-06 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("datasets", "0003_alter_dataset_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Дашборд",
                "verbose_name_plural": "Дашборды",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("bar", "Колонка"),
                            ("line", "Линия"),
                            ("pie", "Пирог"),
                            ("table", "Таблица"),
                        ],
                        max_length=20,
                    ),
                ),
                ("x_column", models.CharField(max_length=100)),
                ("y_column", models.CharField(blank=True, max_length=100)),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="dashboards.dashboard",
                    ),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="widgets",
                        to="datasets.dataset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Виджет",
                "verbose_name_plural": "Виджеты",
                "ordering": ["-created_at"],
            },
        ),
    ]
