# Generated by Django 6.0 on 2026-03-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboards", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="widget",
            name="chart_type",
            field=models.CharField(
                choices=[
                    ("bar", "Столбчатая"),
                    ("line", "Линейная"),
                    ("pie", "Круговая"),
                    ("table", "Таблица"),
                ],
                max_length=20,
            ),
        ),
    ]
