# Generated by Django 6.0 on 2026-03-06 09:55

from django.db import migrations

import apps.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.users.models.UserManager()),
            ],
        ),
    ]
